### PR TITLE
diarizer service

### PR DESCRIPTION
**Pull request by mgood**
Get the diarizer container working with the Go test.

Fixes #62

### CODE REVIEW

**Comment by progrium** [comment]
Do you have any basic info on resource utilization/requirements for the readme?

**Comment by mgood** [comment]
The speakers timespans reported aren't the most accurate, but getting something in that we can iterate on.

I do see a message `WARNING: The NVIDIA Driver was not detected.` So we'll need to investigate that, but running on the NUC this clip took ~20s to run, which is slightly faster than the audio length.

**Comment by mgood** [comment]
Oh, the memory usage processing that audio clip peaked around 1.7G
Image size is 9G
I guess the main README shows total memory usage, so I could just add 2G, though I didn't compare running all of them together at this point.

**Comment by progrium** [comment]
Can you just add that to the services Readme real quick?

**Pull request merged**
